# Site settings
title: git3moji â€” A simple three-letter (or less) emoji standard for expressive commit messages
description: A simple three-letter (or less) emoji standard for expressive commit messages
baseurl: "https://robinpokorny.github.io/git3moji/"

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
exclude: ["README.md"]
sass:
  style: compressed
